version: "2"
services:
    api:
        image: node
        env_file:
            - .env
        ports: 
            - "${PORT}:${PORT}"
        volumes:
            - ./api:/usr/api
        depends_on:
            - db
        working_dir: /usr/api
        environment:
            - MONGO_URI=${MONGO_URI}
            - MONGO_DB_NAME=${MONGO_DB_NAME}
            - API_SECRET=${API_SECRET}
            - PORT=${PORT}
        command: bash -c "npm install && npm start"
        networks:
            - default
    www:
        image: nginx
        env_file:
            - .env
        ports: 
            - "80:80"
        volumes:
            - ./www:/usr/share/nginx/html
        networks:
            - default
    db:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_ROOT_DATABASE=${MONGO_INITDB_ROOT_DATABASE}
        ports:
            - "27017:27017"
        networks:
            - default
volumes:
    persistent: