version: "2"
services:
    api:
        image: node
        ports: 
            - "3000:3000"
        volumes:
            - ./api:/usr/api
        depends_on:
            - db
        working_dir: /usr/api
        environment:
            - MONGO_URI=mongodb://admin:password@db:27017
        command: bash -c "npm install && npm start"
        networks:
            - default
    www:
        image: nginx
        ports: 
            - "80:80"
        volumes:
            - ./www:/usr/share/nginx/html
        networks:
            - default
    db:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_INITDB_ROOT_DATABASE=chat
        ports:
            - "27017:27017"
        networks:
            - default
volumes:
    persistent: