name: Deploy

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * *'

env:
  PRODUCTION: true
  # HTTPS: true
  # API: https://api.barcelos.dev

jobs:
  test-build-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: GuillaumeFalourd/setup-rsync@v1.1

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      - name: Delete OLD Folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            folder="${{secrets.HOME}}/${{secrets.PROJ_NAME}}.barcelos.dev"
            if [ -d "$folder" ]; then
              rm -Rf ${{ secrets.HOME }}/${{secrets.PROJ_NAME}}.barcelos.dev
            fi

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" > ./api/.env
          echo "API_SECRET=${{ secrets.API_SECRET }}" >> ./api/.env
          echo "MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}" >> ./api/.env

      - name: Deploy with rsync
        run: |
          rsync --progress -avz -e "ssh -v -i ~/.ssh/id_rsa" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.HOME }}/${{secrets.PROJ_NAME}}.barcelos.dev/

      - name: Install package in API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.HOME }}/${{secrets.PROJ_NAME}}.barcelos.dev/api
            npm i

      - name: API Start/Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pm2 describe ${{secrets.PM2_PROCESS_NAME}} > /dev/null
            if [ $? -ne 0 ]; then
              echo "Process not found, starting it..."
              pm2 start ${{ secrets.HOME }}/${{secrets.PROJ_NAME}}.barcelos.dev/api/api.js --name ${{secrets.PM2_PROCESS_NAME}}
            else
              pm2 -s restart ${{secrets.PM2_PROCESS_NAME}}
            fi

      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            systemctl reload nginx
